// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/conversation.proto

package conversation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Datecreation  string                 `protobuf:"bytes,2,opt,name=datecreation,proto3" json:"datecreation,omitempty"`
	Nbmessage     int32                  `protobuf:"varint,3,opt,name=nbmessage,proto3" json:"nbmessage,omitempty"`
	Dureevie      int32                  `protobuf:"varint,4,opt,name=dureevie,proto3" json:"dureevie,omitempty"`
	Media         bool                   `protobuf:"varint,5,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_proto_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetDatecreation() string {
	if x != nil {
		return x.Datecreation
	}
	return ""
}

func (x *Conversation) GetNbmessage() int32 {
	if x != nil {
		return x.Nbmessage
	}
	return 0
}

func (x *Conversation) GetDureevie() int32 {
	if x != nil {
		return x.Dureevie
	}
	return 0
}

func (x *Conversation) GetMedia() bool {
	if x != nil {
		return x.Media
	}
	return false
}

type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dureevie      int32                  `protobuf:"varint,1,opt,name=dureevie,proto3" json:"dureevie,omitempty"`
	Media         bool                   `protobuf:"varint,2,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_proto_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConversationRequest) GetDureevie() int32 {
	if x != nil {
		return x.Dureevie
	}
	return 0
}

func (x *CreateConversationRequest) GetMedia() bool {
	if x != nil {
		return x.Media
	}
	return false
}

type CreateConversationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationReply) Reset() {
	*x = CreateConversationReply{}
	mi := &file_proto_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationReply) ProtoMessage() {}

func (x *CreateConversationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationReply.ProtoReflect.Descriptor instead.
func (*CreateConversationReply) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateConversationReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_proto_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteConversationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationReply) Reset() {
	*x = DeleteConversationReply{}
	mi := &file_proto_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationReply) ProtoMessage() {}

func (x *DeleteConversationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationReply.ProtoReflect.Descriptor instead.
func (*DeleteConversationReply) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteConversationReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nbmessage     *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=nbmessage,proto3" json:"nbmessage,omitempty"`
	Dureevie      *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=dureevie,proto3" json:"dureevie,omitempty"`
	Media         *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationRequest) Reset() {
	*x = UpdateConversationRequest{}
	mi := &file_proto_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationRequest) ProtoMessage() {}

func (x *UpdateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateConversationRequest) GetNbmessage() *wrapperspb.Int32Value {
	if x != nil {
		return x.Nbmessage
	}
	return nil
}

func (x *UpdateConversationRequest) GetDureevie() *wrapperspb.Int32Value {
	if x != nil {
		return x.Dureevie
	}
	return nil
}

func (x *UpdateConversationRequest) GetMedia() *wrapperspb.BoolValue {
	if x != nil {
		return x.Media
	}
	return nil
}

type UpdateConversationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nbmessage     *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=nbmessage,proto3" json:"nbmessage,omitempty"`
	Dureevie      *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=dureevie,proto3" json:"dureevie,omitempty"`
	Media         *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationReply) Reset() {
	*x = UpdateConversationReply{}
	mi := &file_proto_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationReply) ProtoMessage() {}

func (x *UpdateConversationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationReply.ProtoReflect.Descriptor instead.
func (*UpdateConversationReply) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateConversationReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateConversationReply) GetNbmessage() *wrapperspb.Int32Value {
	if x != nil {
		return x.Nbmessage
	}
	return nil
}

func (x *UpdateConversationReply) GetDureevie() *wrapperspb.Int32Value {
	if x != nil {
		return x.Dureevie
	}
	return nil
}

func (x *UpdateConversationReply) GetMedia() *wrapperspb.BoolValue {
	if x != nil {
		return x.Media
	}
	return nil
}

type ConversationIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationIdRequest) Reset() {
	*x = ConversationIdRequest{}
	mi := &file_proto_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationIdRequest) ProtoMessage() {}

func (x *ConversationIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationIdRequest.ProtoReflect.Descriptor instead.
func (*ConversationIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *ConversationIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConversationIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationIdResponse) Reset() {
	*x = ConversationIdResponse{}
	mi := &file_proto_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationIdResponse) ProtoMessage() {}

func (x *ConversationIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationIdResponse.ProtoReflect.Descriptor instead.
func (*ConversationIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *ConversationIdResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

var File_proto_conversation_proto protoreflect.FileDescriptor

const file_proto_conversation_proto_rawDesc = "" +
	"\n" +
	"\x18proto/conversation.proto\x12\fconversation\x1a\x1egoogle/protobuf/wrappers.proto\"\x92\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fdatecreation\x18\x02 \x01(\tR\fdatecreation\x12\x1c\n" +
	"\tnbmessage\x18\x03 \x01(\x05R\tnbmessage\x12\x1a\n" +
	"\bdureevie\x18\x04 \x01(\x05R\bdureevie\x12\x14\n" +
	"\x05media\x18\x05 \x01(\bR\x05media\"M\n" +
	"\x19CreateConversationRequest\x12\x1a\n" +
	"\bdureevie\x18\x01 \x01(\x05R\bdureevie\x12\x14\n" +
	"\x05media\x18\x02 \x01(\bR\x05media\")\n" +
	"\x17CreateConversationReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19DeleteConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17DeleteConversationReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd1\x01\n" +
	"\x19UpdateConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\tnbmessage\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\tnbmessage\x127\n" +
	"\bdureevie\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\bdureevie\x120\n" +
	"\x05media\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\x05media\"\xcf\x01\n" +
	"\x17UpdateConversationReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\tnbmessage\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\tnbmessage\x127\n" +
	"\bdureevie\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\bdureevie\x120\n" +
	"\x05media\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\x05media\"'\n" +
	"\x15ConversationIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x16ConversationIdResponse\x12>\n" +
	"\fconversation\x18\x01 \x01(\v2\x1a.conversation.ConversationR\fconversation2\xb2\x03\n" +
	"\x14gestion_conversation\x12f\n" +
	"\x12CreateConversation\x12'.conversation.CreateConversationRequest\x1a%.conversation.CreateConversationReply\"\x00\x12f\n" +
	"\x12DeleteConversation\x12'.conversation.DeleteConversationRequest\x1a%.conversation.DeleteConversationReply\"\x00\x12f\n" +
	"\x12UpdateConversation\x12'.conversation.UpdateConversationRequest\x1a%.conversation.UpdateConversationReply\"\x00\x12b\n" +
	"\x13GetConversationById\x12#.conversation.ConversationIdRequest\x1a$.conversation.ConversationIdResponse\"\x00B-Z+crud-db-conversation-ctn/proto;conversationb\x06proto3"

var (
	file_proto_conversation_proto_rawDescOnce sync.Once
	file_proto_conversation_proto_rawDescData []byte
)

func file_proto_conversation_proto_rawDescGZIP() []byte {
	file_proto_conversation_proto_rawDescOnce.Do(func() {
		file_proto_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_conversation_proto_rawDesc), len(file_proto_conversation_proto_rawDesc)))
	})
	return file_proto_conversation_proto_rawDescData
}

var file_proto_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_conversation_proto_goTypes = []any{
	(*Conversation)(nil),              // 0: conversation.Conversation
	(*CreateConversationRequest)(nil), // 1: conversation.CreateConversationRequest
	(*CreateConversationReply)(nil),   // 2: conversation.CreateConversationReply
	(*DeleteConversationRequest)(nil), // 3: conversation.DeleteConversationRequest
	(*DeleteConversationReply)(nil),   // 4: conversation.DeleteConversationReply
	(*UpdateConversationRequest)(nil), // 5: conversation.UpdateConversationRequest
	(*UpdateConversationReply)(nil),   // 6: conversation.UpdateConversationReply
	(*ConversationIdRequest)(nil),     // 7: conversation.ConversationIdRequest
	(*ConversationIdResponse)(nil),    // 8: conversation.ConversationIdResponse
	(*wrapperspb.Int32Value)(nil),     // 9: google.protobuf.Int32Value
	(*wrapperspb.BoolValue)(nil),      // 10: google.protobuf.BoolValue
}
var file_proto_conversation_proto_depIdxs = []int32{
	9,  // 0: conversation.UpdateConversationRequest.nbmessage:type_name -> google.protobuf.Int32Value
	9,  // 1: conversation.UpdateConversationRequest.dureevie:type_name -> google.protobuf.Int32Value
	10, // 2: conversation.UpdateConversationRequest.media:type_name -> google.protobuf.BoolValue
	9,  // 3: conversation.UpdateConversationReply.nbmessage:type_name -> google.protobuf.Int32Value
	9,  // 4: conversation.UpdateConversationReply.dureevie:type_name -> google.protobuf.Int32Value
	10, // 5: conversation.UpdateConversationReply.media:type_name -> google.protobuf.BoolValue
	0,  // 6: conversation.ConversationIdResponse.conversation:type_name -> conversation.Conversation
	1,  // 7: conversation.gestion_conversation.CreateConversation:input_type -> conversation.CreateConversationRequest
	3,  // 8: conversation.gestion_conversation.DeleteConversation:input_type -> conversation.DeleteConversationRequest
	5,  // 9: conversation.gestion_conversation.UpdateConversation:input_type -> conversation.UpdateConversationRequest
	7,  // 10: conversation.gestion_conversation.GetConversationById:input_type -> conversation.ConversationIdRequest
	2,  // 11: conversation.gestion_conversation.CreateConversation:output_type -> conversation.CreateConversationReply
	4,  // 12: conversation.gestion_conversation.DeleteConversation:output_type -> conversation.DeleteConversationReply
	6,  // 13: conversation.gestion_conversation.UpdateConversation:output_type -> conversation.UpdateConversationReply
	8,  // 14: conversation.gestion_conversation.GetConversationById:output_type -> conversation.ConversationIdResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_conversation_proto_init() }
func file_proto_conversation_proto_init() {
	if File_proto_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_conversation_proto_rawDesc), len(file_proto_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_conversation_proto_goTypes,
		DependencyIndexes: file_proto_conversation_proto_depIdxs,
		MessageInfos:      file_proto_conversation_proto_msgTypes,
	}.Build()
	File_proto_conversation_proto = out.File
	file_proto_conversation_proto_goTypes = nil
	file_proto_conversation_proto_depIdxs = nil
}
